# Generated by Django 5.1.1 on 2024-10-07 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelter", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="shelter_images/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="shelter.shelter",
                    ),
                ),
            ],
        ),
    ]
